# Generated by Django 4.0.8 on 2022-12-26 18:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretitle', tinymce.models.HTMLField(blank=True, verbose_name='Перед Капточкой')),
                ('title', models.CharField(max_length=50, verbose_name='Оглавление')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='Контент')),
            ],
        ),
    ]
