# Generated by Django 4.0.8 on 2023-01-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IrbisPage', '0004_card_for_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Оглавление'),
        ),
    ]
