# Generated by Django 4.0.8 on 2023-01-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IrbisPage', '0005_alter_card_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='link',
            field=models.CharField(blank=True, max_length=50, verbose_name='ссылка'),
        ),
    ]
